### ISSUE TITLE
I don't have a points table. Do I need to make one? This is not mentioned in the README

### ISSUE THREAD

**Issue by ddd1600** [CrossTheStreams/active_record_nearest_neighbor#2]
getting this error when trying out the #close_to command

PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "points"

**Comment by CrossTheStreams** [comment]
Yikes, thanks for this catch! 

The problematic line is here:

https://github.com/CrossTheStreams/active_record_nearest_neighbor/blob/master/lib/active_record_nearest_neighbor/scopes.rb#L14

"points" is the table name I used in the specs, but I missed one spot where I interpolate the table name. I'm merging in a fix to this, along with a couple other changes.

**Comment by CrossTheStreams** [comment]
https://github.com/CrossTheStreams/active_record_nearest_neighbor/compare/master...fix_table_name_bug

**Comment by CrossTheStreams** [comment]
Hey @ddd1600, I've patched several bugs this evening. Please upgrade to 0.3.4. Thanks for bringing some of these bugs to my attention— please let me know if you have any other feedback!

:guitar:

**Comment by CrossTheStreams** [comment]
Please update your gem version to 0.3.4 for the fix for this bug. Thanks again :D
